### ISSUE TITLE
Working with Screen>Plate>Well>Image

### ISSUE THREAD

**Issue by romainGuiet** [GReD-Clermont/omero_macro-extensions#13]
Hi @ppouchin ,

Today one of our user contacted me to process some data that are stored as a screen.

I couldn't find a getScreen(), getPlate() ... so I guess I'll have to modifify some class like : 
```
    /**
     * Retrieves the repository object of the specified type with the specified ID.
     *
     * @param type The type of object.
     * @param id   The object ID.
     *
     * @return The object.
     */
    private GenericRepositoryObjectWrapper<?> getRepositoryObject(String type, long id) {
        String singularType = singularType(type);

        GenericRepositoryObjectWrapper<?> object = null;
        try {
            switch (singularType) {
                case PROJECT:
                    object = client.getProject(id);
                    break;
                case DATASET:
                    object = client.getDataset(id);
                    break;
                case IMAGE:
                    object = client.getImage(id);
                    break;
                case SCREEN:
                    object = client.getScreen(id);
                    break;
                case Plate:
                    object = client.getPlate(id);
                    break;
                case Well:
                    object = client.getWell(id);
                    break;
                default:
                    IJ.error(INVALID + ": " + type + ".");
            }
        } catch (ServiceException | AccessException | ExecutionException e) {
            IJ.error("Could not retrieve object: " + e.getMessage());
        }
        return object;
    }
```

which would require to modify [the simple-omero-client](https://github.com/GReD-Clermont/simple-omero-client/blob/main/src/main/java/fr/igred/omero/Client.java). 

Am I correct ?

Cheers,

R

**Comment by ppouchin** [comment]
You are correct.
It is something I'm trying to implement. I have not done so yet because we don't use screens in our lab currently.

I have been trying to re-work the library a bit ([on this branch](https://github.com/GReD-Clermont/simple-omero-client/tree/rois)), and I've been trying, locally, to add classes for Screens/Plates/Wells.

However, I'm still on the fence as to how I should structure this. I would have made theses classes inherit from "RepositoryObject", but they don't all have a "getName" or "getDescription" method (Wells typically). 

The code itself should be quite straightforward as it's just a matter of method delegation, although adding tests might take longer (as I don't know how to automatically populate HCS... yet).

**Comment by romainGuiet** [comment]
Thanks for your answer!
I followed the link you provided which point to the `rois `branch. I had a look but couldn't find Screen or Plate named classes...
Am I in the wrong branch ?

Is there something I can do to help you? 

I don't know if you need it bu I prepared a [minimal screen with 4 wells and 4 field of view per well](https://drive.switch.ch/index.php/s/pucF45UuXCiLfHo). In omero.insight you just need to select the `index.idx.xml` file to import them.

Cheers

**Comment by ppouchin** [comment]
> I followed the link you provided which points to the `rois `branch.
> I had a look but couldn't find Screen or Plate named classes... Am I in the wrong branch?
> Or is it the Folder that works for Screen , Plate and Well ?

Oh, sorry. I only meant that I'm currently refactoring the library and that I've been trying to add screens locally, but I haven't pushed anything yet.
To be faster, I'm going to try to branch from main and add them there, I'll include it in the refactoring later.

> I don't know if you need it but I prepared a [minimal screen with 4 wells and 4 field of view per well](https://drive.switch.ch/index.php/s/pucF45UuXCiLfHo). In omero.insight you just need to select the `index.idx.xml` file to import them.

Thank you! That will help me understand how everything works. I'll still need to check how to [generate "fake" screens for the automated tests](https://github.com/GReD-Clermont/simple-omero-client/blob/main/.omeroci/test-data), but at least, I'll be able to write the classes.

**Comment by ppouchin** [comment]
It's still a work in progress, but here it is: https://github.com/GReD-Clermont/simple-omero-client/tree/hcs

**Comment by romainGuiet** [comment]
I worked this morning on a groovy script using the new wrappers and I managed to reach what we need, see below for something that works for the dataset I shared earlier!

```
// @String(label="Username") USERNAME
// @String(label="Password", style='password' , value=PASSWORD) PASSWORD
// @String(label="Host", value='wss://workshop.openmicroscopy.org/omero-ws') HOST
// @Integer(label="Port", value=4064) PORT
// @Long(label="ID", value=119273) id
// @String(label="Object", choices={"image", "well","plate","screen"}) object_type
// @Boolean showImages
#@CommandService command
#@RoiManager rm

IJ.run("Close All", "");
rm.reset()

Client user_client = new Client();

user_client.connect("omero-server.epfl.ch", 4064, USERNAME, PASSWORD.toCharArray() );
println "Connection to Omero : Success"

try{
	
	if ( object_type.equals("image") ) {

		processImage( user_client, user_client.getImage(id) )
	
	} else if ( object_type.equals("well") ){

		processWell( user_client, user_client.getWells(id) )
			
	} else if ( object_type.equals("plate") ){
			
		processPlate( user_client, user_client.getPlates(id))
		
	} else if ( object_type.equals("screen") ){
			
		processScreen( user_client, user_client.getScreens(id))
		
	}
	
} finally{
	user_client.disconnect()
	println "Disconnection to Omero , user: Success"
}

println "processing of "+object_type+", id "+id+": DONE !"
return


/*
 *  Helpers function for the different "layers" Image,Well,Plate,Screen
 * 
 */

def ipas(imp,rm) {
	IJ.run(imp, "Find Maxima...", "prominence=10000 output=[Point Selection]");
	multiPoint_roi = imp.getRoi();

	xS = multiPoint_roi.getXCoordinates()
	yS = multiPoint_roi.getYCoordinates()
	
	(0..multiPoint_roi.size()-1).each{
		roi = new PointRoi( xS[it], yS[it])
		rm.addRoi( roi )
	}
}


def processImage(user_client, image_wpr){
	// clear Fiji env
	IJ.run("Close All", "");
	rm.reset()
	
	println image_wpr.getName()
	ImagePlus imp = image_wpr.toImagePlus(user_client);
	if ( showImages ) imp.show()
	
	// delete existing ROIs
	println "Deleting existing OMERO-ROIs"
	image_wpr.getROIs(user_client).each{ user_client.delete(it) }
	
	// do the processing here 
	println "Image Analysis : Start"
	ipas(imp,rm)
	println "Image Analysis : End"
					
	// send ROIs to Omero
	ij_rois = rm.getRoisAsArray() as List
	def rw = new ROIWrapper()
	omero_rois = rw.fromImageJ(ij_rois)	
	omero_rois.each{ image_wpr.saveROI(user_client , it)	}
	println "New ROIs sent to OMERO"
	
}

def processWell(user_client, well_wpr_list){
		
	well_wpr_list.each{ well_wpr ->				
		well_wpr.getWellSamples().each{			
			processImage(user_client, it.getImage())		
		}
	}	
}

def processPlate(user_client, plate_wpr_list){
	
	plate_wpr_list.each{ plate_wpr ->	
		processWell(user_client, plate_wpr.getWells(user_client))
	} 
}

def processScreen(user_client, screen_wpr_list){
	
	screen_wpr_list.each{ screen_wpr ->	
		processPlate(user_client, screen_wpr.getPlates())
	} 
}



/*
 * imports  
 */

import fr.igred.omero.*
import fr.igred.omero.roi.*
import fr.igred.omero.repository.*
import ij.*
import ij.plugin.*
import ij.gui.PointRoi
import ch.epfl.biop.wrappers.cellpose.ij2commands.Cellpose_SegmentImgPlusAdvanced
import ch.epfl.biop.ij2command.*


```

**Comment by ppouchin** [comment]
Ok. I've made a release. If something's missing, another release will fix it.

**Comment by romainGuiet** [comment]
Sorry for the delay with my answer (too many things in parallel here 😅  )
Thanks again,
R

**Comment by ppouchin** [comment]
No problem. That's what I thought, hence why I went ahead with the release: you surely have other things to do!
I realized that "release first, fix later if needed" would be more appropriate.

I do hope this will suit your needs!
